# Site
name: "accessible ai"
title: "accessible ai"
description: "accessible ai - making aritificial intelligence accessible for everyone"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: hello@paraavsingla.com

# Authors
authors:
  parav:
    name: Parav
    display_name: Parav
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: hello@paravsingla.com
    web: https://paravsingla.com
    twitter: https://twitter.com/wowthemesnet
    description: "Parav has been working with Artificial Intelligence and Machine Learning for about five years. He started accessible ai with the goal of making artificial intelligence easier to learn."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
